#!/usr/bin/python
# -*- coding: utf-8 -*- 
__author__ = 'Иван Богданович'

import time

def timer(f):
    def tmp(*args, **kwargs):
        t = time.time()
        res = f(*args, **kwargs)
        print("Время выполнения: %f" % (time.time()-t))
        return res
    return tmp

@timer
def answer(s):
    a = []
    rev_str = s[::-1]
    for i in rev_str:
        if i == 'A': a.append('T')
        elif i == 'C': a.append('G')
        elif i == 'G': a.append('C')
        elif i == 'T': a.append('A')
    print(''.join(a))
dataset = 'TGCCCCACTTTGAAGACCGGAAAAGCAAACAACGGGCAATGAATCTGTCTTCTAGGAAGACTGGGGGCCAGTTCGCCCAGTTCATGAGATTGAGAAAAAGAACAGCTAGTCCTAAGTAGGCTCCTTGCCCGCGTTTTCGCGCTACGCCGTCATCGGTATACGGACGAGACCGCGACTCCTTGGGCGTAATTGTGCCGATGTTCAATTCTTTCCTATCGGACAGGCCGATTTTGTTCACAGCGAGTCTACCTGGAGACTTCCTTGATCTCAGACAGTCGTACTATAAAATGTATGGGTTCAGCTTATCCCTACGGATGTGCAGTACGGGGTGGTTGTCGCCGGTTGGATAAGTGAAAGACCTTTGTACTGCAAAGAACACCATCCTGAAACTCTTCGCTTCGGGCACTTTGGGTCATGTGATAAGTCTAAAGCACTCCCGAAGCTTGCTGAACGACATAGTGCCGTGCTGTCCAAGCTTCTTACAGCCTGAGTTAACTCCTGAGTTACAAAAAACATGTTAGTACGTCGCCAGTGACGGGCGAAGTGTTTTTTCCTAGCACTGCTTATAAAACGCGGCGCCGCGTAAAACTTCCGGGCCTGTTTAGTCCGGAGCATGCATCGCTCTTCCTGTGCGGGAAAAGGCCTCTTAATCGTTATATTGTCAGCCGTTCGGCGCAGCGAGAAAAACGTGAATCTAGCGACTAAATTCAGGAATTAGTTTTAATCCCCCACACAGCGAGTCTTGCCTAAGTCTGTCGCTAGCTGAGCGGAGGCGGATCGGCGATCTTATCGACCATAATTACTGGGCATAGCTCGTCGAGCGAAAAATTAGGGCTCGACAATCGCCTCTCTAACAAGTGTTTTCTCGGTACAACGCCGGCGGTATGCAATACCAAACAAGAGCATCTGCATTGTGTGCAAGCGTGACGTACTTCAGCTTGCGCCATGGTTGAGTAGACCCATGTCCGGCGCTAACAACCTGATC'
answer(dataset)